init:
  - git config --global core.autocrlf true

image: Visual Studio 2015

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build_script:
  - ps: .\build.ps1
  - OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\tests\Valit.Tests\bin\Release\netcoreapp2.0\Valit.Tests.dll -noshadow" -oldstyle -filter:"+[Valit*]* -[Valit.Tests*]*" -output:".\valit_coverage.xml" 
  - codecov -f .\valit_coverage.xml -t $(codecov_token)

test: off

branches:
  only:
    - develop
    - master

cache:
- tools -> build.cake
- packages -> build.cake
