init:
  - git config --global core.autocrlf true

build_script:
  - ps: .\build.ps1
  - choco install codecov
  - codecov -f tests/Valit.Tests/TestResults/valit_tests_result.xml -t $(codecov_token)

test: off

branches:
  only:
    - develop
    - master

cache:
- tools -> build.cake
- packages -> build.cake