init:
  - git config --global core.autocrlf true

build_script:
  - ps: .\build.ps1
  - choco install xunit
  - OpenCover.Console.exe -register:user -target:"xunit.console.x86.exe" -targetargs:".\tests\Valit.Tests\bin\Release\**\Valit.Tests.dll -noshadow" -filter:"+[Valit*]* -[Valit.Tests*]*" -output:".\valit_coverage.xml"
  - choco install codecov
  - codecov -f .\valit_coverage.xml -t $(codecov_token)

test: off

branches:
  only:
    - develop
    - master

cache:
- tools -> build.cake
- packages -> build.cake