coverage:
 range: 60...95
  notify:
    slack:
      default:
        url: $(codecov-webhook)
        threshold: 1%
        only_pulls: false
        branches: 
          - master
          - develop
