coverage:
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 0%
        only_pulls: false
        branches: 
          - master
          - develop
